### ISSUE TITLE
WARNING Message: TypeError: window.manager is undefined whatsapp web

### ISSUE THREAD

**Issue by edwinalex035** [mozilla/webextension-polyfill#187]
Hi,

I have been using whalesong for a while and today, whatsapp web install a new update. After that, the code gave me this warning: WARNING Message: TypeError: window.manager is undefined whatsapp web
Then I tried to run it again and it is giving the following exception:

Traceback (most recent call last):
  File "/home/alexander/PycharmProjects/wappExt/silsol_multimedia.py", line 737, in <module>
    bot.loop.run_until_complete(bot.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/alexander/PycharmProjects/wappExt/silsol_multimedia.py", line 703, in start
    await self._driver.start()
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/whalesong/__init__.py", line 96, in start
    await self._driver.connect()
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 108, in connect
    await self.run_scriptlet()
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/whalesong/driver.py", line 69, in run_scriptlet
    await self._internal_run_scriptlet(script.read())
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 119, in _internal_run_scriptlet
    await self._run_async(self.driver.execute_script, script)
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/whalesong/driver_firefox.py", line 73, in _run_async
    return await self.loop.run_in_executor(self._pool_executor, partial(method, *args, **kwargs))
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/alexander/PycharmProjects/wappExt/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: e[o] is undefined

**Comment by Rob--W** [comment]
This report was posted at the wrong repository, and has since been reposted as issue 106 at https://github.com/alfred82santa/whalesong .
